services:
  db:
    image: postgres:15-alpine
    container_name: gymmax_db
    restart: always
    environment:
      POSTGRES_USER: gymmax_user
      POSTGRES_PASSWORD: gymmax_password
      POSTGRES_DB: gymmax_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
