from .usuario import Usuario
from .plan import Plan
from .suscripcion import Suscripcion
from .pago import Pago
from .asistencia import Asistencia
from .entrenador import Entrenador
from .clase import Clase
from .horario_clase import HorarioClase
from .reserva import Reserva
from .notificacion_clase import NotificacionClase
from .ejercicio import Ejercicio
from .rutina import Rutina
from .dia_rutina import DiaRutina
from .ejercicio_rutina import EjercicioRutina
from .registro_ejercicio import RegistroEjercicio
