"""Add token_app

Revision ID: d12d2366a1ff
Revises: f686bb95d4fb
Create Date: 2026-05-24 16:39:53.148460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12d2366a1ff'
down_revision: Union[str, Sequence[str], None] = 'f686bb95d4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('token_app', sa.String(), nullable=True))
    op.create_index(op.f('ix_usuarios_token_app'), 'usuarios', ['token_app'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_token_app'), table_name='usuarios')
    op.drop_column('usuarios', 'token_app')
    # ### end Alembic commands ###
